---
- name: Provision RHEL hosts
  ec2_instance:
    state: "{{ item.state | default('present') }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ ec2_keypair }}"
    region: "{{ ec2_region }}"
    security_group: "{{ ec2_security_group }}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    name: "{{ item.name }}"
    instance_type: "{{ item.instance_type }}"
    image:
      id: "{{ rhel_ami_id }}"
    user_data: "{{ lookup('template', '../templates/cloud-init.j2') }}"
    network:
      assign_public_ip: true
    wait: true
    tags:
      identity: rhel_lab
  loop: "{{ instances }}"
  register: rhel_lab
