---
- name: Provision AWS instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instances:
      - name: rhel-lab1
        instance_type: t3.large
        state: absent
      - name: rhel-lab2
        instance_type: t2.micro
        state: absent
      - name: aap2-controller1
        instance_type: m4.large
        state: absent

  tasks:
    - name: Include AWS cloud infra role
      ansible.builtin.include_role:
        name: cloud-infra
        tasks_from: aws.yml

    - name: Launch instances
      ansible.builtin.include_role:
        name: cloud-infra
        tasks_from: aws-instances.yml
