Vagrant.configure("2") do |config|
  config.vm.define "tools-lab" do |rhel|
    rhel.vm.box = "generic/rhel8"
    rhel.vm.hostname = "tools-lab"
    rhel.vm.network "private_network", ip: "10.0.1.20", hostname: true

    rhel.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.playbook = "provision.yml"
      ansible.ask_vault_pass = true
    end
  end
  config.vm.provider "virtualbox" do |vb, override|
    vb.memory = 2500
    vb.cpus = 2
  end
end
