Vagrant.configure("2") do |config|
  N = 1
  (1..N).each do |i|
    config.vm.define "aap2-lab#{i}" do |rhel|
      rhel.vm.box = "generic/rhel8"
      rhel.vm.hostname = "aap2-lab#{i}"
      rhel.vm.network "private_network", ip: "10.0.1.#{20+i}", hostname: true

      if i == N
        rhel.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "provision.yml"
          ansible.ask_vault_pass = true
        end
      end
    end
    config.vm.provider "virtualbox" do |vb, override|
      vb.memory = 5000
      vb.cpus = 2
    end
  end
end
